### PR TITLE
Add create project to usage print

### PR DESCRIPTION
**Pull request by Max-Meldrum**
:ireland:

### CODE REVIEW

**Comment by Lilja** [comment]
Good spot!

Could you also edit the `README.md`?

**Comment by flygare** [comment]
LGTM! 👍

**Comment by flygare** [comment]
Closing and opening to trigger build.

**Review by Lilja — APPROVED** [review]

**Comment by Lilja** [comment]
Due to a stupid test this fails when the time is less than 10, will restart the job in a couple of hours

Basically `date +%H` return 09 if the time is 09:00
I've written a test that takes the current time and subtracts it by 1.
So what's being executed is ((09-1)) which isn't 8. It throws that error.

Will restart the job in a couple of hours and it will be fixed lol

**Review by flygare — APPROVED** [review]

**Pull request merged**
